### ISSUE TITLE
decaf demo page offline

### ISSUE THREAD

**Issue by dnouri** [UCB-ICSI-Vision-Group/decaf-release#6]
DeCAF's demo page with the impressive ImageNet demo has gone offline since the Christmas holidays.  Can we have it back?  :-)
http://decaf.berkeleyvision.org/

**Comment by tarungarg1121** [comment]
DeCAF's demo page with the impressive ImageNet demo has gone offline since the Christmas holidays. Can we have it back? :-) 
please provide  other link

**Comment by Yangqing** [comment]
(After so many months/years I think I should have closure on Decaf... Just in case you are wondering, the demo page is now at

http://demo.caffe.berkeleyvision.org/
)
