### ISSUE TITLE
unrecognized option -Wl

### ISSUE THREAD

**Issue by jpfarias** [UCB-ICSI-Vision-Group/decaf-release#9]
Hi, when I run python setup.py build on both my mac and linux machines I get an error while compiling: unrecognized option: "-Wl"

I edited the file layers/cpp/Makefile and removed the -Wl from the linking options and it built and installed just fine. I am not sure what that option does but that is how I made it work for me.

Thank you!

**Comment by Yangqing** [comment]
(It is a lingering flag that should be removed... Changed. Probably no longer important as we've deprecated decaf for a while :))
